"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-15 12:40:41.418004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_user')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_user_email'))
    )
    op.create_table('category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], name=op.f('fk_category_parent_id_category'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    op.create_table('currency',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_currency'))
    )
    op.create_table('locale',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_locale'))
    )
    op.create_table('media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('alt', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    op.create_index(op.f('ix_media_owner_id'), 'media', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_owner_type'), 'media', ['owner_type'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'awaiting_payment', 'paid', 'fulfilled', 'completed', 'cancelled', 'refunded', name='order_status', native_enum=False, length=32), nullable=False),
    sa.Column('region_code', sa.String(length=16), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('shipping_fee', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_orders_idempotency_key')),
    sa.UniqueConstraint('number', name=op.f('uq_orders_number'))
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='product_status', native_enum=False, length=32), nullable=False),
    sa.Column('product_type', sa.String(length=64), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_index(op.f('ix_product_status'), 'product', ['status'], unique=False)
    op.create_table('category_translation',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.String(length=512), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_category_translation_category_id_category'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locale'], ['locale.code'], name=op.f('fk_category_translation_locale_locale'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'locale', name=op.f('pk_category_translation')),
    sa.UniqueConstraint('locale', 'slug', name='uq_category_translation_locale_slug')
    )
    op.create_index(op.f('ix_category_translation_slug'), 'category_translation', ['slug'], unique=False)
    op.create_table('exchange_rate',
    sa.Column('base_code', sa.String(length=3), nullable=False),
    sa.Column('quote_code', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['base_code'], ['currency.code'], name=op.f('fk_exchange_rate_base_code_currency'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_code'], ['currency.code'], name=op.f('fk_exchange_rate_quote_code_currency'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('base_code', 'quote_code', name=op.f('pk_exchange_rate'))
    )
    op.create_table('order_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('draft', 'awaiting_payment', 'paid', 'fulfilled', 'completed', 'cancelled', 'refunded', name='order_status', native_enum=False, length=32), nullable=True),
    sa.Column('to_status', sa.Enum('draft', 'awaiting_payment', 'paid', 'fulfilled', 'completed', 'cancelled', 'refunded', name='order_status', native_enum=False, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_event_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_event'))
    )
    op.create_index(op.f('ix_order_event_order_id'), 'order_event', ['order_id'], unique=False)
    op.create_table('order_line',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('variant_label', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_line_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_line'))
    )
    op.create_index(op.f('ix_order_line_order_id'), 'order_line', ['order_id'], unique=False)
    op.create_table('product_category',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_product_category_category_id_category'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_category_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id', name=op.f('pk_product_category'))
    )
    op.create_table('product_option',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_option_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_option'))
    )
    op.create_index(op.f('ix_product_option_product_id'), 'product_option', ['product_id'], unique=False)
    op.create_table('product_translation',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.String(length=512), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['locale'], ['locale.code'], name=op.f('fk_product_translation_locale_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_translation_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'locale', name=op.f('pk_product_translation')),
    sa.UniqueConstraint('locale', 'slug', name='uq_product_translation_locale_slug')
    )
    op.create_index(op.f('ix_product_translation_slug'), 'product_translation', ['slug'], unique=False)
    op.create_table('product_variant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_variant_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variant')),
    sa.UniqueConstraint('sku', name=op.f('uq_product_variant_sku'))
    )
    op.create_index(op.f('ix_product_variant_product_id'), 'product_variant', ['product_id'], unique=False)
    op.create_table('region',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], name=op.f('fk_region_currency_code_currency')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_region'))
    )
    op.create_table('cart',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('region_code', sa.String(length=16), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('active', 'converted', 'abandoned', name='cart_status', native_enum=False, length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], name=op.f('fk_cart_currency_code_currency')),
    sa.ForeignKeyConstraint(['region_code'], ['region.code'], name=op.f('fk_cart_region_code_region')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart')),
    sa.UniqueConstraint('token', name=op.f('uq_cart_token'))
    )
    op.create_table('inventory_item',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], name=op.f('fk_inventory_item_variant_id_product_variant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id', name=op.f('pk_inventory_item'))
    )
    op.create_table('option_value',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('option_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['product_option.id'], name=op.f('fk_option_value_option_id_product_option'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_option_value'))
    )
    op.create_index(op.f('ix_option_value_option_id'), 'option_value', ['option_id'], unique=False)
    op.create_table('product_option_translation',
    sa.Column('option_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['locale'], ['locale.code'], name=op.f('fk_product_option_translation_locale_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['product_option.id'], name=op.f('fk_product_option_translation_option_id_product_option'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('option_id', 'locale', name=op.f('pk_product_option_translation'))
    )
    op.create_table('region_locale',
    sa.Column('region_code', sa.String(length=16), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['locale'], ['locale.code'], name=op.f('fk_region_locale_locale_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_code'], ['region.code'], name=op.f('fk_region_locale_region_code_region'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('region_code', 'locale', name=op.f('pk_region_locale'))
    )
    op.create_table('region_payment_method',
    sa.Column('region_code', sa.String(length=16), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['region_code'], ['region.code'], name=op.f('fk_region_payment_method_region_code_region'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('region_code', 'provider_code', name=op.f('pk_region_payment_method'))
    )
    op.create_table('stock_movement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], name=op.f('fk_stock_movement_variant_id_product_variant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movement'))
    )
    op.create_index(op.f('ix_stock_movement_variant_id'), 'stock_movement', ['variant_id'], unique=False)
    op.create_table('variant_price',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], name=op.f('fk_variant_price_currency_code_currency')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], name=op.f('fk_variant_price_variant_id_product_variant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id', 'currency_code', name=op.f('pk_variant_price'))
    )
    op.create_table('cart_line',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name=op.f('fk_cart_line_cart_id_cart'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], name=op.f('fk_cart_line_variant_id_product_variant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_line'))
    )
    op.create_index(op.f('ix_cart_line_cart_id'), 'cart_line', ['cart_id'], unique=False)
    op.create_table('option_value_translation',
    sa.Column('option_value_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['locale'], ['locale.code'], name=op.f('fk_option_value_translation_locale_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_value_id'], ['option_value.id'], name=op.f('fk_option_value_translation_option_value_id_option_value'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('option_value_id', 'locale', name=op.f('pk_option_value_translation'))
    )
    op.create_table('variant_option_value',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('option_value_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['option_value_id'], ['option_value.id'], name=op.f('fk_variant_option_value_option_value_id_option_value'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], name=op.f('fk_variant_option_value_variant_id_product_variant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id', 'option_value_id', name=op.f('pk_variant_option_value'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant_option_value')
    op.drop_table('option_value_translation')
    op.drop_index(op.f('ix_cart_line_cart_id'), table_name='cart_line')
    op.drop_table('cart_line')
    op.drop_table('variant_price')
    op.drop_index(op.f('ix_stock_movement_variant_id'), table_name='stock_movement')
    op.drop_table('stock_movement')
    op.drop_table('region_payment_method')
    op.drop_table('region_locale')
    op.drop_table('product_option_translation')
    op.drop_index(op.f('ix_option_value_option_id'), table_name='option_value')
    op.drop_table('option_value')
    op.drop_table('inventory_item')
    op.drop_table('cart')
    op.drop_table('region')
    op.drop_index(op.f('ix_product_variant_product_id'), table_name='product_variant')
    op.drop_table('product_variant')
    op.drop_index(op.f('ix_product_translation_slug'), table_name='product_translation')
    op.drop_table('product_translation')
    op.drop_index(op.f('ix_product_option_product_id'), table_name='product_option')
    op.drop_table('product_option')
    op.drop_table('product_category')
    op.drop_index(op.f('ix_order_line_order_id'), table_name='order_line')
    op.drop_table('order_line')
    op.drop_index(op.f('ix_order_event_order_id'), table_name='order_event')
    op.drop_table('order_event')
    op.drop_table('exchange_rate')
    op.drop_index(op.f('ix_category_translation_slug'), table_name='category_translation')
    op.drop_table('category_translation')
    op.drop_index(op.f('ix_product_status'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_media_owner_type'), table_name='media')
    op.drop_index(op.f('ix_media_owner_id'), table_name='media')
    op.drop_table('media')
    op.drop_table('locale')
    op.drop_table('currency')
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    op.drop_table('category')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
